// pages/index.js
import React from 'react';
import Head from 'next/head';
import styles from '../styles/Home.module.css';

const products = [
  {
    id: 1,
    name: 'Cheese Raclette Machine',
    price: 250.00, // Changed to number type
    image: '/images/cheese-raclette.jpg',
  },
  {
    id: 2,
    name: 'Round Table',
    price: 179.00, // Changed to number type
    image: '/images/round-table.jpg',
  },
  // Add more products as needed
];

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>E-commerce Site</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>E-commerce Site</h1>

        <div className={styles.grid}>
          {products.map((product) => (
            <div key={product.id} className={styles.card}>
              <img src={product.image} alt={`Image of ${product.name}`} className={styles.productImage} /> {/* Improved alt text */}
              <h2>{product.name}</h2>
              <p>{product.price.toFixed(2)} €</p> {/* Ensure price is displayed with two decimal places */}
              <button className={styles.button}>Add to Cart</button>
            </div>
          ))}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <img src="/vercel.svg" alt="Vercel Logo" />
          </span>
        </a>
      </footer>
    </div>
  );
}
